#!/bin/bash
if [ ! -f mod_cluster-1.3.1.Final-linux2-x64-ssl.tar.gz ]; then
    wget http://downloads.jboss.org/mod_cluster//1.3.1.Final/linux-x86_64/mod_cluster-1.3.1.Final-linux2-x64-ssl.tar.gz
fi
docker build -t nonymus/modcluster .
